import React from 'react'
import Head from 'next/head'
import {AiOutlineArrowRight} from 'react-icons/ai'
import {DataItem} from "../data.js"

function menu() {
  return (
    <>
    <Head>
    <title>Menu page</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Photo.png" />
  </Head>


  <header className="grid grid-cols-2 items-center h-[100vh] ">
    <div className='header-content'>
        
        <div className='content-main flex flex-col items-center justify-center'>
            <h1 className="font-bold text-2xl mb-[20px]">Delicious food for your cravings</h1>
            <p>We made fresh and healthy meals with different recipes</p>
            <button className="flex items-center justify-center gap-[20px] bg-yellow-200 w-[250px] p-2 mt-[30px]" >View Menu <AiOutlineArrowRight/></button>
        </div>
    </div>
    <img src="/f13.jpeg" className='header-img w-[380px] rounded-full align-center'/>
    </header>

    <div className="MenuContainer grid grid-cols-2 md:grid-cols-5 gap-[25px]">
        {
            DataItem.map((item)=>{
                return (
                    <div key={item.id} className="MenuContent flex flex-col items-center justify-center">
                        <div className='flex flex-col items-center justify-center'>
                        <img src={item.image} className='header-img w-[100px] h-[100px] rounded-full align-center'/>
                        <div className="flex flex-col items-center justify-center">
                        <span className="font-bold">{item.name}</span>
                        <span className='text-[#FFE145] font-bold'>#{item.price}</span></div>
                        </div>
                        
                        <div>
                          <p className="text-sm text-center">{item.desc}</p>
                        </div>

                        <div className="flex justify-between items-center gap-[40px]">
                            <button className="font-bold text-2xl">+</button>
                            <button className="font-bold text-2xl">-</button>
                        </div>


                    </div>
                )
            })
        }

    </div>
      
    </>
  )
}

export default menu
