import React from 'react'
import Head from 'next/head'
import {AiOutlineArrowRight} from 'react-icons/ai'
import {DataItem} from "../data.js"
import { connect } from 'react-redux';
import {useDispatch} from 'react-redux'
import { cartActions } from '../Redux/store/cartslice';
import Image from "next/image"
import Navbar from './Components/Navbar.jsx';
import Footer from './Components/Footer.jsx';

function Menu() {
  const dispatch = useDispatch()
  return (
    <>
    <Head>
    <title>Menu page</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Photo.png" />
  </Head>

<Navbar/>
  <header className="grid grid-cols-2 items-center h-[100vh] ">
    <div className='header-content'>
        
        <div className='content-main flex flex-col p-4 md:ml-[100px]'>
            <h1 className="font-bold text-2xl mb-[20px]">Delicious food for your cravings</h1>
            <p className="md:w-[300px]">We made fresh and healthy meals with different recipes</p>
            <button className="flex items-center justify-center gap-[20px] bg-yellow-200 w-[200px] p-2 mt-[30px]" >View Menu <AiOutlineArrowRight/></button>
        </div>
    </div>
    <div>
    <Image width={500} height={500} alt="image" src="/f13.jpeg" className='header-img rounded-full align-center'/></div>
    </header>

    <div className="MenuContainer grid grid-cols-2 md:grid-cols-5 gap-[25px]">
        {
            DataItem.map((item)=>{
                return (
                    <div key={item.id} className="MenuContent flex flex-col items-center justify-center">
                        <div className='flex flex-col items-center justify-center'>
                        <Image  width={150} height={150} alt="image" src={item.image} className='header-img w-[100px] h-[100px] rounded-full align-center'/>
                        <div className="flex flex-col items-center justify-center">
                        <span className="font-bold">{item.name}</span>
                        <span className='text-[#FFE145] font-bold'>#{item.price}</span></div>
                        </div>
                        
                        <div>
                          <p className="text-sm text-center">{item.desc}</p>
                        </div>

                        <div className="flex justify-between items-center gap-[40px]">
                            <button className="font-bold text-2xl  p-2 w-[50px]" onClick={()=>dispatch(cartActions.addtocart(item))}>+</button>
                        
                        </div>


                    </div>
                )
            })
        }

    </div>


    <Footer/>
      
    </>
  )
}

export default Menu
