import React from 'react'
import Head from 'next/head'

function signup() {
  return (
    <>
     <Head>
        <title>Sign Up page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Photo.png" />
      </Head>
     <div className="h-screen flex items-center justify-center">

<div className="flex items-center justify-center flex-col">
<img src="/Logo.png"/>
  <form className="flex items-center justify-center flex-col">
    <div className="m-[20px]"><h2 className="font-bold text-center text-2xl">SIGN UP</h2>
    <p className="text-center">Hello, Create an Account here</p>
    </div>
    <div><input type="email" placeholder="info@gmail.com" className="border-2 border-yellow-200 focus:outline-none w-[300px] p-2"/></div>
    <div><input type="password" placeholder="*******"  className="border-2 border-yellow-200 focus:outline-none w-[300px] p-2 mt-[20px]"/></div>
    <div><button  className="border-2 border-yellow-200 bg-yellow-200 mt-[20px] focus:outline-none w-[300px] p-2">Sign Up</button></div>
  </form>
</div>

</div>
      
    </>
  )
}

export default signup
